src/Entity/HistoriqueEnchere.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\HistoriqueEnchereRepository")
 */
class HistoriqueEnchere
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $date_enchere;

    /**
     * @ORM\Column(type="float")
     */
    private $prix;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Utilisateur", inversedBy="historiqueEnchere")
     */
    private $utilisateur;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Enchere", inversedBy="historiqueEnchere")
     */
    private $enchere;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateEnchere(): ?\DateTimeInterface
    {
        return $this->date_enchere;
    }

    public function setDateEnchere(\DateTimeInterface $date_enchere): self
    {
        $this->date_enchere = $date_enchere;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getUtilisateur(): ?Utilisateur
    {
        return $this->utilisateur;
    }

    public function setUtilisateur(?Utilisateur $utilisateur): self
    {
        $this->utilisateur = $utilisateur;

        return $this;
    }

    public function getEnchere(): ?Enchere
    {
        return $this->enchere;
    }

    public function setEnchere(?Enchere $enchere): self
    {
        $this->enchere = $enchere;

        return $this;
    }
    public function __toString()
    {
        return strval($this->prix);
    }
}

src/Form/HistoriqueEnchereType.php
<?php

namespace App\Form;

use App\Entity\HistoriqueEnchere;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class HistoriqueEnchereType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('date_enchere')
            ->add('prix')
            ->add('utilisateur')
            ->add('enchere')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => HistoriqueEnchere::class,
        ]);
    }
}

src/Controller/HistoriqueEnchereController.php
<?php

namespace App\Controller;

use App\Entity\HistoriqueEnchere;
use App\Form\HistoriqueEnchereType;
use App\Repository\HistoriqueEnchereRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/historique/enchere")
 */
class HistoriqueEnchereController extends AbstractController
{
    /**
     * @Route("/", name="historique_enchere_index", methods={"GET"})
     */
    public function index(HistoriqueEnchereRepository $historiqueEnchereRepository): Response
    {
        return $this->render('historique_enchere/index.html.twig', [
            'historique_encheres' => $historiqueEnchereRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="historique_enchere_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $historiqueEnchere = new HistoriqueEnchere();
        $form = $this->createForm(HistoriqueEnchereType::class, $historiqueEnchere);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($historiqueEnchere);
            $entityManager->flush();

            return $this->redirectToRoute('historique_enchere_index');
        }

        return $this->render('historique_enchere/new.html.twig', [
            'historique_enchere' => $historiqueEnchere,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="historique_enchere_show", methods={"GET"})
     */
    public function show(HistoriqueEnchere $historiqueEnchere): Response
    {
        return $this->render('historique_enchere/show.html.twig', [
            'historique_enchere' => $historiqueEnchere,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="historique_enchere_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, HistoriqueEnchere $historiqueEnchere): Response
    {
        $form = $this->createForm(HistoriqueEnchereType::class, $historiqueEnchere);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('historique_enchere_index');
        }

        return $this->render('historique_enchere/edit.html.twig', [
            'historique_enchere' => $historiqueEnchere,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="historique_enchere_delete", methods={"DELETE"})
     */
    public function delete(Request $request, HistoriqueEnchere $historiqueEnchere): Response
    {
        if ($this->isCsrfTokenValid('delete'.$historiqueEnchere->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($historiqueEnchere);
            $entityManager->flush();
        }

        return $this->redirectToRoute('historique_enchere_index');
    }
}

templates/historique_enchere/_delete_form.html.twig
<form method="post" action="{{ path('historique_enchere_delete', {'id': historique_enchere.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ historique_enchere.id) }}">
    <button class="btn">Delete</button>
</form>

templates/historique_enchere/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/historique_enchere/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit HistoriqueEnchere{% endblock %}

{% block body %}
    <h1>Edit HistoriqueEnchere</h1>

    {{ include('historique_enchere/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('historique_enchere_index') }}">back to list</a>

    {{ include('historique_enchere/_delete_form.html.twig') }}
{% endblock %}

templates/historique_enchere/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}HistoriqueEnchere index{% endblock %}

{% block body %}
    <h1>HistoriqueEnchere index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Date_enchere</th>
                <th>Prix</th>
                <th>Utilisateur</th>
                <th>Enchere</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for historique_enchere in historique_encheres %}
            <tr>
                <td>{{ historique_enchere.id }}</td>
                <td>{{ historique_enchere.dateEnchere ? historique_enchere.dateEnchere|date('Y-m-d') : '' }}</td>
                <td>{{ historique_enchere.prix }}</td>
                <td>{{ historique_enchere.utilisateur }}</td>
                <td>{{ historique_enchere.enchere }}</td>
                <td>
                    <a href="{{ path('historique_enchere_show', {'id': historique_enchere.id}) }}">show</a>
                    <a href="{{ path('historique_enchere_edit', {'id': historique_enchere.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('historique_enchere_new') }}">Create new</a>
{% endblock %}

templates/historique_enchere/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New HistoriqueEnchere{% endblock %}

{% block body %}
    <h1>Create new HistoriqueEnchere</h1>

    {{ include('historique_enchere/_form.html.twig') }}

    <a href="{{ path('historique_enchere_index') }}">back to list</a>
{% endblock %}

templates/historique_enchere/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}HistoriqueEnchere{% endblock %}

{% block body %}
    <h1>HistoriqueEnchere</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ historique_enchere.id }}</td>
            </tr>
            <tr>
                <th>Date_enchere</th>
                <td>{{ historique_enchere.dateEnchere ? historique_enchere.dateEnchere|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Prix</th>
                <td>{{ historique_enchere.prix }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('historique_enchere_index') }}">back to list</a>

    <a href="{{ path('historique_enchere_edit', {'id': historique_enchere.id}) }}">edit</a>

    {{ include('historique_enchere/_delete_form.html.twig') }}
{% endblock %}