src/Entity/Enchere.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\EnchereRepository")
 */
class Enchere
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     *
     */
    private $numero;

    /**
     * @ORM\Column(type="date")
     */
    private $date_debut;

    /**
     * @ORM\Column(type="date")
     */
    private $date_fin;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\HistoriqueEnchere", mappedBy="enchere")
     */
    private $historiqueEnchere;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Produit", inversedBy="enchere")
     * @ORM\JoinColumn(nullable=false)
     */
    private $produit;

    public function __construct()
    {
        $this->historiqueEnchere = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumero(): ?int
    {
        return $this->numero;
    }

    public function setNumero(int $numero): self
    {
        $this->numero = $numero;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeInterface $date_debut): self
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(\DateTimeInterface $date_fin): self
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    /**
     * @return Collection|HistoriqueEnchere[]
     */
    public function getHistoriqueEnchere(): Collection
    {
        return $this->historiqueEnchere;
    }

    public function addHistoriqueEnchere(HistoriqueEnchere $historiqueEnchere): self
    {
        if (!$this->historiqueEnchere->contains($historiqueEnchere)) {
            $this->historiqueEnchere[] = $historiqueEnchere;
            $historiqueEnchere->setEnchere($this);
        }

        return $this;
    }

    public function removeHistoriqueEnchere(HistoriqueEnchere $historiqueEnchere): self
    {
        if ($this->historiqueEnchere->contains($historiqueEnchere)) {
            $this->historiqueEnchere->removeElement($historiqueEnchere);
            // set the owning side to null (unless already changed)
            if ($historiqueEnchere->getEnchere() === $this) {
                $historiqueEnchere->setEnchere(null);
            }
        }

        return $this;
    }

    public function getProduit(): ?Produit
    {
        return $this->produit;
    }

    public function setProduit(?Produit $produit): self
    {
        $this->produit = $produit;

        return $this;
    }
    public function __toString()
    {
        return strval($this->id);
    }
}

src/Form/EnchereType.php
<?php

namespace App\Form;

use App\Entity\Enchere;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EnchereType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('numero')
            ->add('date_debut')
            ->add('date_fin')
            ->add('produit')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Enchere::class,
        ]);
    }
}

src/Controller/EnchereController.php
<?php

namespace App\Controller;

use App\Entity\Enchere;
use App\Form\EnchereType;
use App\Repository\EnchereRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/enchere")
 */
class EnchereController extends AbstractController
{
    /**
     * @Route("/", name="enchere_index", methods={"GET"})
     */
    public function index(EnchereRepository $enchereRepository): Response
    {
        return $this->render('enchere/index.html.twig', [
            'encheres' => $enchereRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="enchere_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $enchere = new Enchere();
        $form = $this->createForm(EnchereType::class, $enchere);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($enchere);
            $entityManager->flush();

            return $this->redirectToRoute('enchere_index');
        }

        return $this->render('enchere/new.html.twig', [
            'enchere' => $enchere,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="enchere_show", methods={"GET"})
     */
    public function show(Enchere $enchere): Response
    {
        return $this->render('enchere/show.html.twig', [
            'enchere' => $enchere,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="enchere_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Enchere $enchere): Response
    {
        $form = $this->createForm(EnchereType::class, $enchere);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('enchere_index');
        }

        return $this->render('enchere/edit.html.twig', [
            'enchere' => $enchere,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="enchere_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Enchere $enchere): Response
    {
        if ($this->isCsrfTokenValid('delete'.$enchere->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($enchere);
            $entityManager->flush();
        }

        return $this->redirectToRoute('enchere_index');
    }
}

templates/enchere/_delete_form.html.twig
<form method="post" action="{{ path('enchere_delete', {'id': enchere.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ enchere.id) }}">
    <button class="btn">Delete</button>
</form>

templates/enchere/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/enchere/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Enchere{% endblock %}

{% block body %}
    <h1>Edit Enchere</h1>

    {{ include('enchere/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('enchere_index') }}">back to list</a>

    {{ include('enchere/_delete_form.html.twig') }}
{% endblock %}

templates/enchere/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Enchere index{% endblock %}

{% block body %}
    <h1>Enchere index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Numero</th>
                <th>Produit</th>
                <th>Date_debut</th>
                <th>Date_fin</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for enchere in encheres %}
            <tr>
                <td>{{ enchere.id }}</td>
                <td>{{ enchere.numero }}</td>
                <td>{{ enchere.produit }}</td>
                <td>{{ enchere.dateDebut ? enchere.dateDebut|date('Y-m-d') : '' }}</td>
                <td>{{ enchere.dateFin ? enchere.dateFin|date('Y-m-d') : '' }}</td>
                <td>
                    <a href="{{ path('enchere_show', {'id': enchere.id}) }}">show</a>
                    <a href="{{ path('enchere_edit', {'id': enchere.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('enchere_new') }}">Create new</a>
{% endblock %}

templates/enchere/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Enchere{% endblock %}

{% block body %}
    <h1>Create new Enchere</h1>

    {{ include('enchere/_form.html.twig') }}

    <a href="{{ path('enchere_index') }}">back to list</a>
{% endblock %}

templates/enchere/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Enchere{% endblock %}

{% block body %}
    <h1>Enchere</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ enchere.id }}</td>
            </tr>
            <tr>
                <th>Numero</th>
                <td>{{ enchere.numero }}</td>
            </tr>
            <tr>
                <th>Produit</th>
                <td>{{ enchere.produit }}</td>
            </tr>
            <tr>
                <th>Date_debut</th>
                <td>{{ enchere.dateDebut ? enchere.dateDebut|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Date_fin</th>
                <td>{{ enchere.dateFin ? enchere.dateFin|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('enchere_index') }}">back to list</a>

    <a href="{{ path('enchere_edit', {'id': enchere.id}) }}">edit</a>

    {{ include('enchere/_delete_form.html.twig') }}
{% endblock %}