src/Entity/Achat.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AchatRepository")
 */
class Achat
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $date_achat;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Utilisateur", inversedBy="achat")
     */
    private $utilisateur;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\PackJeton", inversedBy="achats")
     */
    private $packJeton;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateAchat(): ?\DateTimeInterface
    {
        return $this->date_achat;
    }

    public function setDateAchat(\DateTimeInterface $date_achat): self
    {
        $this->date_achat = $date_achat;

        return $this;
    }

    public function getUtilisateur(): ?Utilisateur
    {
        return $this->utilisateur;
    }

    public function setUtilisateur(?Utilisateur $utilisateur): self
    {
        $this->utilisateur = $utilisateur;

        return $this;
    }

    public function getPackJeton(): ?PackJeton
    {
        return $this->packJeton;
    }

    public function setPackJeton(?PackJeton $packJeton): self
    {
        $this->packJeton = $packJeton;

        return $this;
    }

    public function __toString()
    {
        return strval($this->id);
    }
}

src/Form/AchatType.php
<?php

namespace App\Form;

use App\Entity\Achat;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AchatType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('date_achat')
            ->add('utilisateur')
            ->add('packJeton')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Achat::class,
        ]);
    }
}

src/Controller/AchatController.php
<?php

namespace App\Controller;

use App\Entity\Achat;
use App\Form\AchatType;
use App\Repository\AchatRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/achat")
 */
class AchatController extends AbstractController
{
    /**
     * @Route("/", name="achat_index", methods={"GET"})
     */
    public function index(AchatRepository $achatRepository): Response
    {
        return $this->render('achat/index.html.twig', [
            'achats' => $achatRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="achat_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $achat = new Achat();
        $form = $this->createForm(AchatType::class, $achat);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($achat);
            $entityManager->flush();

            return $this->redirectToRoute('achat_index');
        }

        return $this->render('achat/new.html.twig', [
            'achat' => $achat,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="achat_show", methods={"GET"})
     */
    public function show(Achat $achat): Response
    {
        return $this->render('achat/show.html.twig', [
            'achat' => $achat,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="achat_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Achat $achat): Response
    {
        $form = $this->createForm(AchatType::class, $achat);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('achat_index');
        }

        return $this->render('achat/edit.html.twig', [
            'achat' => $achat,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="achat_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Achat $achat): Response
    {
        if ($this->isCsrfTokenValid('delete'.$achat->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($achat);
            $entityManager->flush();
        }

        return $this->redirectToRoute('achat_index');
    }
}

templates/achat/_delete_form.html.twig
<form method="post" action="{{ path('achat_delete', {'id': achat.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ achat.id) }}">
    <button class="btn btn-danger mt-3 mb-3 ml-3">Delete</button>
</form>

templates/achat/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-success mt-3 mb-3">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/achat/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Achat{% endblock %}

{% block body %}
    <h1>Edit Achat</h1>
    <div class="jumbotron">

    {{ include('achat/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('achat_index') }}">revenir à la liste</a>

    {{ include('achat/_delete_form.html.twig') }}
    </div>
{% endblock %}

templates/achat/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Achat index{% endblock %}

{% block body %}
    <div class="jumbotron">
    <h1 class="bg-dark d-block text-white">La liste des achats</h1>

    <table class="table jumbotron">
        <thead>
            <tr>
                <th>Id</th>
                <th>Date_achat</th>
                <th>Utilisateur</th>
                <th>Pack Jeton</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for achat in achats %}
            <tr>
                <td>{{ achat.id }}</td>
                <td>{{ achat.dateAchat ? achat.dateAchat|date('Y-m-d') : '' }}</td>
                <td>{{ achat.utilisateur }}</td>
                <td>{{ achat.packJeton }}</td>
                <td class="d-block d-md-block display-4">
                    <a href="{{ path('achat_show', {'id': achat.id}) }}" class="btn btn-primary">Voir</a>
                    <a href="{{ path('achat_edit', {'id': achat.id}) }}" class="btn btn-success mr-3">Modifier</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('achat_new') }}" class="btn btn-primary">Creation achat</a>
    </div>
{% endblock %}

templates/achat/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Achat{% endblock %}

{% block body %}
    <div class="container mt-5 mb-3">
        <div class="jumbotron">
            <h1 class="bg-dark text-white">Création de l'achat</h1>

            {{ include('achat/_form.html.twig') }}

            <a href="{{ path('achat_index') }}" class="btn btn-primary">retourner à la liste d'achat</a>
            <div >
    </div>
{% endblock %}

templates/achat/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Achat{% endblock %}

{% block body %}
    <div class="container">
    <h1>Achat<a href="{{ path('achat_index') }}" class="btn btn-primary float-right mr-3 mt-3 mb-3">retour à la liste</a></h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <th>Utilisateur</th>
                <th>PackJeton</th>
                <th>Date_achat</th>
                <th>Action</th>

            </tr>
            <tr>
                <td>{{ achat.id }}</td>
                <td>{{ achat.utilisateur }}</td>
                <td>{{ achat.packJeton }}</td>
                <td>{{ achat.dateAchat ? achat.dateAchat|date('Y-m-d') : '' }}</td>
                <td class=""> <a href="{{ path('achat_edit', {'id': achat.id}) }}" class="btn btn-success">modifier</a></td>

            </tr>

        </tbody>
    </table>
    <p class="float-right">{{ include('achat/_delete_form.html.twig') }}</p>
    </div>
{% endblock %}